version: '3.9'

services:
  db:
    image: postgres:15-alpine3.21
    container_name: clube_do_romance_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 20s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      
  adminer:
    image: adminer:4.8.1
    container_name: clube_adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    depends_on:
      - db

volumes:
  db_data: